name: learn-github-actions
on:
  [push]
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: develop
      - name: Push File
        run: |
          TEST=$(<version.txt)
          echo "$((TEST+1))"