name: learn-github-actions
on:
  [push]
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: develop
      - name: Push File
        run: |
          VERSION='cat version.txt'
          a=1
          echo "$((VERSION+a))" >> version.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push origin develop
