name: learn-github-actions
on:
  pull_request:
    types: [opened]
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        id: set-value
        run: |
          labels=github.event.pull_request.labels.*.name
          echo '::set-output name=lavel::${labels}'
      - name: Step2
        uses: actions/checkout@v2
      - name: Step3
        run: |   
          echo ${{steps.set-value.outputs.label}} >> hello.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push